merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:band_id>/', views.band_detail, name='band-detail'),
    path('bands/add', views.band_create, name='band-create'),
    path('bands/<int:band_id>/change/', views.band_update, name='band-update'),

    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:listing_id>/',
         views.listing_detail, name='listing-detail'),
    path('listings/add', views.listing_create, name='listing-create'),
    path('listings/<int:listing_id>/change/',
         views.listing_update, name='listing-update'),

    path('about-us/', views.about, name='a-propos'),
    path('contact-us/', views.contact, name='contact'),
    path('sent-mail/', views.sent_mail, name='sent-mail')
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.


class Band(models.Model):
    def __str__(self):
        return f'{self.name}'

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    name = models.fields.CharField(max_length=100)
    bibliography = models.fields.CharField(max_length=50)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2021)])
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)


class Listing(models.Model):
    class Type(models.TextChoices):
        Records = 'Records'
        Clothing = 'Clothing'
        Posters = 'Posters'
        Micellaneous = 'Micellaneous'
    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.FloatField(default=20)
    year = models.fields.IntegerField(null=True, blank=True)
    type = models.fields.CharField(choices=Type.choices, max_length=20)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

merchex/listings/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from listings.models import Band
from listings.models import Listing
from listings.form import ContactUsForm, BandForm, ListingForm
from django.core.mail import send_mail

# Create your views here.


def band_list(request):
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html', {'bands': bands})


def band_detail(request, band_id):
    band = Band.objects.get(id=band_id)
    return render(request, 'listings/band_detail.html', {'band': band})


def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm()
    return render(request, 'listings/band_create.html', {'form': form})


def band_update(request, band_id):
    band = Band.objects.get(id=band_id)
    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)
    return render(request, 'listings/band_update.html', {'form': form})


def about(request):
    return render(request, 'listings/about.html')


def listing_list(request):
    listings = Listing.objects.all()
    return render(request, 'listings/listing_list.html', {'listings': listings})


def listing_detail(request, listing_id):
    listing = Listing.objects.get(id=listing_id)
    return render(request, 'listings/listing_detail.html', {'listing': listing})


def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            listing = form.save()
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm()
    return render(request, 'listings/listing_create.html', {'form': form})


def listing_update(request, listing_id):
    listing = Listing.objects.get(id=listing_id)
    if request.method == "POST":
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            listing = form.save()
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm(instance=listing)
    return render(request, 'listings/listing_update.html', {'form': form})


def contact(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
                subject=f'message from {form.cleaned_data["name"] or "Anonyme"} Via Merchex Contact-us form',
                message=form.cleaned_data["message"],
                from_email=form.cleaned_data["email"],
                recipient_list=['donaldtitembaye@gmail.com'],)
            return redirect('sent-mail')
    else:
        form = ContactUsForm()
    return render(request, 'listings/contact.html', {'form': form})


def sent_mail(request):
    return render(request, 'listings/sent_mail.html')

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>A propos de nous</h1>
{% endblock %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Creer un nouveau groupe</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>
{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{band.name}}</h2>
<ul>
    <li>Genre: {{band.genre}}</li>
    <li>Année de formation: {{year_formed}}</li>
    <li>Actif: {{band.active}}</li>
    {{band.official_homepage}}
</ul>
<p>{{band.biography}}</p>
<a href="{% url 'band-update' band.id %}">Editer ce groupe</a>
<a href="{% url 'band-list' %}">Retour à tous les groupes</a>

{% for listing in band.listing_set.all %}
<h3><a href="{% url 'listing-list' %}">{{listing.title}}</a></h3>
{% endfor %}
{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content%}
    <h1>Groupes</h1>
    <a href="{% url 'band-create' %}">Nouveau Groupe</a>
    <ul>
        {% for band in bands %}
        <li>
            <a href="{% url 'band-detail' band.id %}">{{band.name}}</a>
            -<a href="{% url 'band-update' band.id %}">[Editer]</a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}
   

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Mise à jour d'un groupe</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Envoyer">
    </form>
{% endblock %}

merchex/listings/templates/listings/base.html
 {% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Merchex</title>
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}">
</head>
<body>
    <a href="{% url 'band-list' %}">Groupes</a>
    <a href="{% url 'listing-list' %}">Annonces</a>
    <a href="{% url 'contact' %}">Contact</a>
    <a href="{% url 'a-propos' %}">A propos</a>
    {% block content %}
    {% endblock%}
</body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html'%}

{% block content %}
    <p>Nous sommes là pour vous aider</p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Envoyer">
    </form>
{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>Creer une nouvelle Annonnce</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>
{% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{listing.title}}</h2>

<p>{{listing.description}}</p>
<ul>
    <li>Solde: {{listing.sold}} </li>
    <li>Année de formation: {{listing.year_formed}} </li>
    <li>Type: {{listing.type}} </li>
    <li>Groupe: {{listing.band.name}} </li>
</ul>
<a href="{% url 'listing-update' listing.id %}">Editer cette annonce</a>
<a href="{% url 'listing-list' %}">Retouner à la liste des annonces</a>
{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html'%}

{% block content %}

<h1>Ma liste de groupe</h1>
<a href="{% url 'listing-create' %}">Nouvelle Annonce</a>
<ul>
    {% for listing in listings %}
    <li>
        <a href="{% url 'listing-detail' listing.id %}">{{listing.title}}</a>
        -<a href="{% url 'listing-update' listing.id %}">[Editer]</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Envoyer">
    </form>
{% endblock %}

merchex/listings/templates/listings/sent_mail.html
{% extends 'listings/base.html' %}

{% block content %}
    <p>Merci de nous avoir contacté</p>
    <h2>Mail Envoyé avec succès</h2>
{% endblock %}